/** Refresh pinned, public reference assets. No API key is needed. */
import { createHash } from 'node:crypto';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { BIBLE_BOOKS } from '../packages/core/src/catalogData';
import { termOccurrences, type TermStatistics } from '../packages/core/src/keyTermScoring';

const sources = {
  text: 'https://bereanbible.com/bsb.txt',
  passages: 'https://a.openbible.info/data/bible-section-counts.txt'
};
async function load(url: string, local?: string) {
  if (local) return readFile(local, 'utf8');
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Reference download: ${response.status}`);
  return response.text();
}
const [text, passages] = await Promise.all([
  load(sources.text, process.env.BSB_TEXT_FILE),
  load(sources.passages, process.env.BIBLE_PASSAGES_FILE)
]);
const names = new Map(BIBLE_BOOKS.map(b => [b.label, b]));
names.set('Psalm', names.get('Psalms')!);
const verses: Record<string, string[]> = {};
const chapters = new Map<string, string[]>();
const stats: TermStatistics = {};
for (const line of text.replace(/^\uFEFF/, '').split(/\r?\n/)) {
  const match = /^(.*?) (\d+):(\d+)\t(.*)$/.exec(line);
  if (!match) continue;
  const book = names.get(match[1]!);
  if (!book) throw new Error(`Unknown BSB book: ${match[1]}`);
  const chapter = Number(match[2]), verse = Number(match[3]);
  if (verse < 1 || verse > (book.verses[chapter - 1] ?? 0)) {
    throw new Error(`Invalid verse: ${match[0]?.slice(0, 40)}`);
  }
  const ordinal = book.verses.slice(0, chapter - 1).reduce((a, b) => a + b, 0) + verse;
  (verses[book.itemId] ??= [])[ordinal - 1] = match[4]!;
  const key = `${book.itemId}:${chapter}`;
  const document = chapters.get(key) ?? [];
  document.push(match[4]!); chapters.set(key, document);
}
for (const book of BIBLE_BOOKS) {
  const expected = book.verses.reduce((a, b) => a + b, 0);
  if (verses[book.itemId]?.length !== expected ||
    Array.from({ length: expected }, (_, i) => verses[book.itemId]?.[i]).some(v => v === undefined)) {
    throw new Error(`Missing verses in ${book.label}`);
  }
}
for (const document of chapters.values()) {
  const seen = new Set<string>();
  for (const verse of document) for (const [term, positions] of termOccurrences(verse)) {
    const entry = stats[term] ??= [0, 0];
    entry[1] += positions.length;
    if (!seen.has(term)) { entry[0]++; seen.add(term); }
  }
}
// Retain all single words and repeated phrases; rare phrases aren't candidates.
for (const term of Object.keys(stats)) if (term.includes(' ') && stats[term]![1] < 3) delete stats[term];
const osis = ('Gen Exod Lev Num Deut Josh Judg Ruth 1Sam 2Sam 1Kgs 2Kgs ' +
  '1Chr 2Chr Ezra Neh Esth Job Ps Prov Eccl Song Isa Jer Lam Ezek Dan Hos ' +
  'Joel Amos Obad Jonah Mic Nah Hab Zeph Hag Zech Mal Matt Mark Luke John ' +
  'Acts Rom 1Cor 2Cor Gal Eph Phil Col 1Thess 2Thess 1Tim 2Tim Titus Phlm ' +
  'Heb Jas 1Pet 2Pet 1John 2John 3John Jude Rev').split(' ');
const sections: Record<string, number[][]> = {};
function reference(value: string) {
  const [code, chapterRaw, verseRaw] = value.split('.');
  const book = BIBLE_BOOKS[osis.indexOf(code!)];
  const chapter = Number(chapterRaw);
  // BSB combines the final greeting in 3 John into verse 14.
  const verse = code === '3John' && chapter === 1 && verseRaw === '15'
    ? 14 : Number(verseRaw);
  if (!book || verse < 1 || verse > (book.verses[chapter - 1] ?? 0)) throw new Error(`Bad passage reference ${value}`);
  return { book, ordinal: book.verses.slice(0, chapter - 1).reduce((a, b) => a + b, 0) + verse };
}
for (const line of passages.split(/\r?\n/)) {
  if (!line || line.startsWith('#')) continue;
  const [startRaw, endRaw, , countRaw] = line.split('\t');
  const start = reference(startRaw!), end = reference(endRaw!);
  const count = Number(countRaw);
  if (start.book !== end.book || end.ordinal < start.ordinal || !Number.isInteger(count) || count < 1 || count > 20) throw new Error(`Bad section ${line}`);
  (sections[start.book.itemId] ??= []).push([start.ordinal, end.ordinal, count]);
}
const directory = new URL('../packages/core/src/bibleData/', import.meta.url);
await mkdir(directory, { recursive: true });
await writeFile(new URL('books.json', directory), JSON.stringify(BIBLE_BOOKS));
for (const [filename, name, value, type] of [
  ['text', 'BSB_VERSES', verses, 'Record<string, string[]>'],
  ['sections', 'BIBLE_SECTIONS', sections, 'Record<string, number[][]>'],
  ['statistics', 'BSB_STATISTICS', stats, 'Record<string, [number, number]>']
] as const) {
  await writeFile(new URL(`${filename}.ts`, directory),
    `// Generated by scripts/buildBibleData.ts. See manifest.json.\nexport const ${name}: ${type} = ${JSON.stringify(value)};\n`);
}
await writeFile(new URL('manifest.json', directory), JSON.stringify({
  version: 1, scorerVersion: 1, documents: chapters.size,
  sources, textLicense: 'Public domain',
  textNotice: text.replace(/^\uFEFF/, '').split(/\r?\n/).slice(0, 2).map(s => s.trim()).join(' '),
  passagesDescription: 'Observed section boundaries across 20 translations; not every possible verse range.',
  versification: { '3John.1.15': '3John.1.14 (BSB)' },
  sha256: { text: createHash('sha256').update(text).digest('hex'),
    passages: createHash('sha256').update(passages).digest('hex') },
  verseCount: Object.values(verses).reduce((n, v) => n + v.length, 0),
  sectionCount: Object.values(sections).reduce((n, v) => n + v.length, 0)
}, null, 2) + '\n');
console.log(`Built ${chapters.size} chapters and ${Object.keys(stats).length} term statistics.`);
