/**
 * Generates packages/core/src/catalogData.ts from LangQuest v2's template
 * migrations (the `template_structure` seed rows for `bible` and `fia`).
 *
 *   npx tsx scripts/buildCatalog.ts ../langquest
 *
 * Re-run when v2's templates change and commit the generated file; the
 * catalog version in packages/core/src/catalog.ts is bumped by hand.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const v2 = process.argv[2];
if (!v2) {
  console.error('usage: tsx scripts/buildCatalog.ts <path to langquest v2 checkout>');
  process.exit(2);
}
const bibleSql = readFileSync(resolve(v2, 'supabase/migrations/20260501150000_add_template_bible_records.sql'), 'utf8');
const fiaSql = readFileSync(resolve(v2, 'supabase/migrations/20260501151000_add_template_fia_records.sql'), 'utf8');

// (NULL,'bible','any','book','Genesis','gen',50,1000,'{"verses":[31,...]}')
const bookRe = /\(NULL,'bible','any','book','([^']+)','([a-z0-9]+)',(\d+),(\d+),'(\{"verses":\[[\d,]+\]\})'\)/g;
const books: { itemId: string; label: string; order: number; verses: number[] }[] = [];
for (const m of bibleSql.matchAll(bookRe)) {
  books.push({ itemId: m[2]!, label: m[1]!, order: Number(m[4]), verses: (JSON.parse(m[5]!) as { verses: number[] }).verses });
}
books.sort((a, b) => a.order - b.order);

// ((SELECT id FROM inserted_book), 'fia', 'any', 'pericope', 'Genesis 1:1-2:3', 'gen-p1', 34, 1001, '{...}'::jsonb)
const periRe = /\(\(SELECT id FROM inserted_book\), 'fia', 'any', 'pericope', '([^']+)', '([a-z0-9-]+)', (\d+), (\d+), '(\{[^']*\})'::jsonb\)/g;
const pericopes: { itemId: string; book: string; label: string; order: number; verseRange: string }[] = [];
for (const m of fiaSql.matchAll(periRe)) {
  const meta = JSON.parse(m[5]!) as { verseRange: string };
  pericopes.push({ itemId: m[2]!, book: m[2]!.split('-')[0]!, label: m[1]!, order: Number(m[4]), verseRange: meta.verseRange });
}
// Keep file order (canonical, then sequence); two pericopes can share an order index in v2.
const fiaBooks = new Set(pericopes.map((p) => p.book));
for (const b of books) if (!fiaBooks.has(b.itemId)) console.warn(`no FIA pericopes for ${b.itemId}`);

const out = `// Generated by scripts/buildCatalog.ts from LangQuest v2 template_structure seeds. Do not edit.
/* eslint-disable */
export interface BibleBook { itemId: string; label: string; order: number; verses: number[] }
export interface FiaPericope { itemId: string; book: string; label: string; order: number; verseRange: string }
export const BIBLE_BOOKS: BibleBook[] = ${JSON.stringify(books)};
export const FIA_PERICOPES: FiaPericope[] = ${JSON.stringify(pericopes)};
`;
const dest = resolve(process.cwd(), 'packages/core/src/catalogData.ts');
writeFileSync(dest, out);
console.log(`wrote ${books.length} books (${books.reduce((a, b) => a + b.verses.length, 0)} chapters) and ${pericopes.length} pericopes to ${dest}`);
