"""Import a pinned bsb-align archive; never extract untrusted archive paths.

Run after buildBibleData.ts. Supply a downloaded tar.gz as the sole argument.
Timings only apply to the Hays narration, never to another audio edition.
"""
import hashlib
import json
from pathlib import Path
import re
import sys
import tarfile

COMMIT = 'bdb859afc427b215b78e12ee4a7798c32b7b91e0'
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'packages/core/src/bibleData'
BOOK_CODES = ('GEN EXO LEV NUM DEU JOS JDG RUT 1SA 2SA 1KI 2KI 1CH 2CH '
              'EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZK DAN HOS '
              'JOL AMO OBA JON MIC NAM HAB ZEP HAG ZEC MAL MAT MRK LUK '
              'JHN ACT ROM 1CO 2CO GAL EPH PHP COL 1TH 2TH 1TI 2TI TIT '
              'PHM HEB JAS 1PE 2PE 1JN 2JN 3JN JUD REV').split()


def generated(name):
    content = (OUT / name).read_text()
    return json.loads(content.split(' = ', 1)[1].rstrip(';\n'))


def words(text):
    return re.findall(r'[^\W\d_]+', text.lower().replace('’', "'"))


verses = generated('text.ts')
# The build script supplies canonical counts in a compact interchange file.
books = json.loads((OUT / 'books.json').read_text())
archive = Path(sys.argv[1])
timings = {}
accepted = 0
rejected = 0
seen = set()
with tarfile.open(archive, 'r:gz') as tar:
    license_member = next(m for m in tar.getmembers()
                          if m.name == f'bsb-align-{COMMIT}/LICENSE')
    (OUT / 'alignment-LICENSE.txt').write_bytes(
        tar.extractfile(license_member).read())
    for member in tar:
        match = re.fullmatch(
            rf'bsb-align-{COMMIT}/output/([^/]+)/[^/]+_(\d+)_words.json',
            member.name)
        if not match:
            continue
        code, chapter = match[1], int(match[2])
        if code not in BOOK_CODES:
            raise ValueError(f'Unknown alignment book {code}')
        book = books[BOOK_CODES.index(code)]
        key = (book['itemId'], chapter)
        if key in seen:
            raise ValueError(f'Duplicate chapter {key}')
        seen.add(key)
        count = book['verses'][chapter - 1]
        offset = sum(book['verses'][:chapter - 1])
        raw = json.load(tar.extractfile(member))['verses']
        result = []
        previous_end = 0
        for verse in range(1, count + 1):
            aligned = raw.get(str(verse), [])
            expected = verses[book['itemId']][offset + verse - 1]
            valid = bool(aligned) and words(' '.join(w['text'] for w in aligned)) == words(expected)
            if aligned:
                valid = valid and all(
                    isinstance(w.get('start'), (int, float)) and
                    isinstance(w.get('end'), (int, float)) and
                    0 <= w['start'] < w['end'] and
                    (i == 0 or w['start'] >= aligned[i-1]['end'])
                    for i, w in enumerate(aligned))
                valid = valid and aligned[0]['start'] >= previous_end
                valid = valid and sum(w.get('score', 0) for w in aligned) / len(aligned) >= .65
            if valid:
                result.append([aligned[0]['start'], aligned[-1]['end']])
                previous_end = aligned[-1]['end']
                accepted += 1
            else:
                result.append(None)
                rejected += 1
        timings.setdefault(book['itemId'], {})[str(chapter)] = result

if len(seen) != 1189:
    raise ValueError(f'Expected 1189 chapters, found {len(seen)}')
(OUT / 'timings.ts').write_text(
    '// Generated by scripts/importBibleTimings.py. Hays narration only.\n'
    'export const BSB_HAYS_TIMINGS: Record<string, Record<string, '
    '([number, number] | null)[]>> = ' + json.dumps(timings, separators=(',', ':')) + ';\n')
(OUT / 'timings-manifest.json').write_text(json.dumps({
    'repository': 'https://github.com/BSB-publishing/bsb-align',
    'commit': COMMIT,
    'archiveSha256': hashlib.sha256(archive.read_bytes()).hexdigest(),
    'narration': 'Barry Hays',
    'audioBase': 'https://openbible.com/audio/hays/',
    'license': 'MIT; see alignment-LICENSE.txt',
    'acceptedVerses': accepted,
    'rejectedVerses': rejected,
    'validation': 'Text match, positive ordered word spans, mean score >= 0.65. Unverified spans use full chapter audio.'
}, indent=2) + '\n')
print(f'Imported {accepted} verse spans; {rejected} use chapter fallback.')
