// Whole chapters of the World English Bible (public domain) for the chapters
// the demo's stories divide into passages (the UX demo's src/chapterText.ts).
// Keyed "book chapter" by core's book ids; verse n is at index n - 1.

export const CHAPTER_TEXT: Record<string, string[]> = {
  "luk 14": [
    "When he went into the house of one of the rulers of the Pharisees on a Sabbath to eat bread, they were watching him.",
    "Behold, a certain man who had dropsy was in front of him.",
    "Jesus, answering, spoke to the lawyers and Pharisees, saying, “Is it lawful to heal on the Sabbath?”",
    "But they were silent. He took him, and healed him, and let him go.",
    "He answered them, “Which of you, if your son or an ox fell into a well, wouldn’t immediately pull him out on a Sabbath day?”",
    "They couldn’t answer him regarding these things.",
    "He spoke a parable to those who were invited, when he noticed how they chose the best seats, and said to them,",
    "“When you are invited by anyone to a marriage feast, don’t sit in the best seat, since perhaps someone more honorable than you might be invited by him,",
    "and he who invited both of you would come and tell you, ‘Make room for this person.’ Then you would begin, with shame, to take the lowest place.",
    "But when you are invited, go and sit in the lowest place, so that when he who invited you comes, he may tell you, ‘Friend, move up higher.’ Then you will be honored in the presence of all who sit at the table with you.",
    "For everyone who exalts himself will be humbled, and whoever humbles himself will be exalted.”",
    "He also said to the one who had invited him, “When you make a dinner or a supper, don’t call your friends, nor your brothers, nor your kinsmen, nor rich neighbors, or perhaps they might also return the favor, and pay you back.",
    "But when you make a feast, ask the poor, the maimed, the lame, or the blind;",
    "and you will be blessed, because they don’t have the resources to repay you. For you will be repaid in the resurrection of the righteous.”",
    "When one of those who sat at the table with him heard these things, he said to him, “Blessed is he who will feast in God’s Kingdom!”",
    "But he said to him, “A certain man made a great supper, and he invited many people.",
    "He sent out his servant at supper time to tell those who were invited, ‘Come, for everything is ready now.’",
    "They all as one began to make excuses. “The first said to him, ‘I have bought a field, and I must go and see it. Please have me excused.’",
    "“Another said, ‘I have bought five yoke of oxen, and I must go try them out. Please have me excused.’",
    "“Another said, ‘I have married a wife, and therefore I can’t come.’",
    "“That servant came, and told his lord these things. Then the master of the house, being angry, said to his servant, ‘Go out quickly into the streets and lanes of the city, and bring in the poor, maimed, blind, and lame.’",
    "“The servant said, ‘Lord, it is done as you commanded, and there is still room.’",
    "“The lord said to the servant, ‘Go out into the highways and hedges, and compel them to come in, that my house may be filled.",
    "For I tell you that none of those men who were invited will taste of my supper.’”",
    "Now great multitudes were going with him. He turned and said to them,",
    "“If anyone comes to me, and doesn’t disregard his own father, mother, wife, children, brothers, and sisters, yes, and his own life also, he can’t be my disciple.",
    "Whoever doesn’t bear his own cross, and come after me, can’t be my disciple.",
    "For which of you, desiring to build a tower, doesn’t first sit down and count the cost, to see if he has enough to complete it?",
    "Or perhaps, when he has laid a foundation, and is not able to finish, everyone who sees begins to mock him,",
    "saying, ‘This man began to build, and wasn’t able to finish.’",
    "Or what king, as he goes to encounter another king in war, will not sit down first and consider whether he is able with ten thousand to meet him who comes against him with twenty thousand?",
    "Or else, while the other is yet a great way off, he sends an envoy, and asks for conditions of peace.",
    "So therefore whoever of you who doesn’t renounce all that he has, he can’t be my disciple.",
    "Salt is good, but if the salt becomes flat and tasteless, with what do you season it?",
    "It is fit neither for the soil nor for the manure pile. It is thrown out. He who has ears to hear, let him hear.”",
  ],
  "luk 15": [
    "Now all the tax collectors and sinners were coming close to him to hear him.",
    "The Pharisees and the scribes murmured, saying, “This man welcomes sinners, and eats with them.”",
    "He told them this parable.",
    "“Which of you men, if you had one hundred sheep, and lost one of them, wouldn’t leave the ninety-nine in the wilderness, and go after the one that was lost, until he found it?",
    "When he has found it, he carries it on his shoulders, rejoicing.",
    "When he comes home, he calls together his friends and his neighbors, saying to them, ‘Rejoice with me, for I have found my sheep which was lost!’",
    "I tell you that even so there will be more joy in heaven over one sinner who repents, than over ninety-nine righteous people who need no repentance.",
    "Or what woman, if she had ten drachma coins, if she lost one drachma coin, wouldn’t light a lamp, sweep the house, and seek diligently until she found it?",
    "When she has found it, she calls together her friends and neighbors, saying, ‘Rejoice with me, for I have found the drachma which I had lost.’",
    "Even so, I tell you, there is joy in the presence of the angels of God over one sinner repenting.”",
    "He said, “A certain man had two sons.",
    "The younger of them said to his father, ‘Father, give me my share of your property.’ He divided his livelihood between them.",
    "Not many days after, the younger son gathered all of this together and traveled into a far country. There he wasted his property with riotous living.",
    "When he had spent all of it, there arose a severe famine in that country, and he began to be in need.",
    "He went and joined himself to one of the citizens of that country, and he sent him into his fields to feed pigs.",
    "He wanted to fill his belly with the husks that the pigs ate, but no one gave him any.",
    "But when he came to himself he said, ‘How many hired servants of my father’s have bread enough to spare, and I’m dying with hunger!",
    "I will get up and go to my father, and will tell him, “Father, I have sinned against heaven, and in your sight.",
    "I am no more worthy to be called your son. Make me as one of your hired servants.”’",
    "“He arose, and came to his father. But while he was still far off, his father saw him, and was moved with compassion, and ran, and fell on his neck, and kissed him.",
    "The son said to him, ‘Father, I have sinned against heaven, and in your sight. I am no longer worthy to be called your son.’",
    "“But the father said to his servants, ‘Bring out the best robe, and put it on him. Put a ring on his hand, and shoes on his feet.",
    "Bring the fattened calf, kill it, and let us eat, and celebrate;",
    "for this, my son, was dead, and is alive again. He was lost, and is found.’ They began to celebrate.",
    "“Now his elder son was in the field. As he came near to the house, he heard music and dancing.",
    "He called one of the servants to him, and asked what was going on.",
    "He said to him, ‘Your brother has come, and your father has killed the fattened calf, because he has received him back safe and healthy.’",
    "But he was angry, and would not go in. Therefore his father came out, and begged him.",
    "But he answered his father, ‘Behold, these many years I have served you, and I never disobeyed a commandment of yours, but you never gave me a goat, that I might celebrate with my friends.",
    "But when this your son came, who has devoured your living with prostitutes, you killed the fattened calf for him.’",
    "“He said to him, ‘Son, you are always with me, and all that is mine is yours.",
    "But it was appropriate to celebrate and be glad, for this, your brother, was dead, and is alive again. He was lost, and is found.’”",
  ],
  "luk 16": [
    "He also said to his disciples, “There was a certain rich man who had a manager. An accusation was made to him that this man was wasting his possessions.",
    "He called him, and said to him, ‘What is this that I hear about you? Give an accounting of your management, for you can no longer be manager.’",
    "“The manager said within himself, ‘What will I do, seeing that my lord is taking away the management position from me? I don’t have strength to dig. I am ashamed to beg.",
    "I know what I will do, so that when I am removed from management, they may receive me into their houses.’",
    "Calling each one of his lord’s debtors to him, he said to the first, ‘How much do you owe to my lord?’",
    "He said, ‘A hundred batos of oil.’ He said to him, ‘Take your bill, and sit down quickly and write fifty.’",
    "Then he said to another, ‘How much do you owe?’ He said, ‘A hundred cors of wheat.’ He said to him, ‘Take your bill, and write eighty.’",
    "“His lord commended the dishonest manager because he had done wisely, for the children of this world are, in their own generation, wiser than the children of the light.",
    "I tell you, make for yourselves friends by means of unrighteous mammon, so that when you fail, they may receive you into the eternal tents.",
    "He who is faithful in a very little is faithful also in much. He who is dishonest in a very little is also dishonest in much.",
    "If therefore you have not been faithful in the unrighteous mammon, who will commit to your trust the true riches?",
    "If you have not been faithful in that which is another’s, who will give you that which is your own?",
    "No servant can serve two masters, for either he will hate the one, and love the other; or else he will hold to one, and despise the other. You aren’t able to serve God and Mammon.”",
    "The Pharisees, who were lovers of money, also heard all these things, and they scoffed at him.",
    "He said to them, “You are those who justify yourselves in the sight of men, but God knows your hearts. For that which is exalted among men is an abomination in the sight of God.",
    "The law and the prophets were until John. From that time the Good News of God’s Kingdom is preached, and everyone is forcing his way into it.",
    "But it is easier for heaven and earth to pass away, than for one tiny stroke of a pen in the law to fall.",
    "Everyone who divorces his wife, and marries another, commits adultery. He who marries one who is divorced from a husband commits adultery.",
    "“Now there was a certain rich man, and he was clothed in purple and fine linen, living in luxury every day.",
    "A certain beggar, named Lazarus, was taken to his gate, full of sores,",
    "and desiring to be fed with the crumbs that fell from the rich man’s table. Yes, even the dogs came and licked his sores.",
    "The beggar died, and he was carried away by the angels to Abraham’s bosom. The rich man also died, and was buried.",
    "In Hades, he lifted up his eyes, being in torment, and saw Abraham far off, and Lazarus at his bosom.",
    "He cried and said, ‘Father Abraham, have mercy on me, and send Lazarus, that he may dip the tip of his finger in water, and cool my tongue! For I am in anguish in this flame.’",
    "“But Abraham said, ‘Son, remember that you, in your lifetime, received your good things, and Lazarus, in the same way, bad things. But here he is now comforted, and you are in anguish.",
    "Besides all this, between us and you there is a great gulf fixed, that those who want to pass from here to you are not able, and that no one may cross over from there to us.’",
    "“He said, ‘I ask you therefore, father, that you would send him to my father’s house;",
    "for I have five brothers, that he may testify to them, so they won’t also come into this place of torment.’",
    "“But Abraham said to him, ‘They have Moses and the prophets. Let them listen to them.’",
    "“He said, ‘No, father Abraham, but if one goes to them from the dead, they will repent.’",
    "“He said to him, ‘If they don’t listen to Moses and the prophets, neither will they be persuaded if one rises from the dead.’”",
  ],
  "gen 1": [
    "In the beginning, God created the heavens and the earth.",
    "The earth was formless and empty. Darkness was on the surface of the deep and God’s Spirit was hovering over the surface of the waters.",
    "God said, “Let there be light,” and there was light.",
    "God saw the light, and saw that it was good. God divided the light from the darkness.",
    "God called the light “day”, and the darkness he called “night”. There was evening and there was morning, the first day.",
    "God said, “Let there be an expanse in the middle of the waters, and let it divide the waters from the waters.”",
    "God made the expanse, and divided the waters which were under the expanse from the waters which were above the expanse; and it was so.",
    "God called the expanse “sky”. There was evening and there was morning, a second day.",
    "God said, “Let the waters under the sky be gathered together to one place, and let the dry land appear”; and it was so.",
    "God called the dry land “earth”, and the gathering together of the waters he called “seas”. God saw that it was good.",
    "God said, “Let the earth yield grass, herbs yielding seeds, and fruit trees bearing fruit after their kind, with their seeds in it, on the earth”; and it was so.",
    "The earth yielded grass, herbs yielding seed after their kind, and trees bearing fruit, with their seeds in it, after their kind; and God saw that it was good.",
    "There was evening and there was morning, a third day.",
    "God said, “Let there be lights in the expanse of the sky to divide the day from the night; and let them be for signs to mark seasons, days, and years;",
    "and let them be for lights in the expanse of the sky to give light on the earth”; and it was so.",
    "God made the two great lights: the greater light to rule the day, and the lesser light to rule the night. He also made the stars.",
    "God set them in the expanse of the sky to give light to the earth,",
    "and to rule over the day and over the night, and to divide the light from the darkness. God saw that it was good.",
    "There was evening and there was morning, a fourth day.",
    "God said, “Let the waters abound with living creatures, and let birds fly above the earth in the open expanse of the sky.”",
    "God created the large sea creatures and every living creature that moves, with which the waters swarmed, after their kind, and every winged bird after its kind. God saw that it was good.",
    "God blessed them, saying, “Be fruitful, and multiply, and fill the waters in the seas, and let birds multiply on the earth.”",
    "There was evening and there was morning, a fifth day.",
    "God said, “Let the earth produce living creatures after their kind, livestock, creeping things, and animals of the earth after their kind”; and it was so.",
    "God made the animals of the earth after their kind, and the livestock after their kind, and everything that creeps on the ground after its kind. God saw that it was good.",
    "God said, “Let us make man in our image, after our likeness: and let them have dominion over the fish of the sea, and over the birds of the sky, and over the livestock, and over all the earth, and over every creeping thing that creeps on the earth.”",
    "God created man in his own image. In God’s image he created him; male and female he created them.",
    "God blessed them. God said to them, “Be fruitful, multiply, fill the earth, and subdue it. Have dominion over the fish of the sea, over the birds of the sky, and over every living thing that moves on the earth.”",
    "God said, “Behold, I have given you every herb yielding seed, which is on the surface of all the earth, and every tree, which bears fruit yielding seed. It will be your food.",
    "To every animal of the earth, and to every bird of the sky, and to everything that creeps on the earth, in which there is life, I have given every green herb for food;” and it was so.",
    "God saw everything that he had made, and, behold, it was very good. There was evening and there was morning, a sixth day.",
  ],
  "gen 2": [
    "The heavens, the earth, and all their vast array were finished.",
    "On the seventh day God finished his work which he had done; and he rested on the seventh day from all his work which he had done.",
    "God blessed the seventh day, and made it holy, because he rested in it from all his work of creation which he had done.",
    "This is the history of the generations of the heavens and of the earth when they were created, in the day that Yahweh God made the earth and the heavens.",
    "No plant of the field was yet in the earth, and no herb of the field had yet sprung up; for Yahweh God had not caused it to rain on the earth. There was not a man to till the ground,",
    "but a mist went up from the earth, and watered the whole surface of the ground.",
    "Yahweh God formed man from the dust of the ground, and breathed into his nostrils the breath of life; and man became a living soul.",
    "Yahweh God planted a garden eastward, in Eden, and there he put the man whom he had formed.",
    "Out of the ground Yahweh God made every tree to grow that is pleasant to the sight, and good for food, including the tree of life in the middle of the garden and the tree of the knowledge of good and evil.",
    "A river went out of Eden to water the garden; and from there it was parted, and became the source of four rivers.",
    "The name of the first is Pishon: it flows through the whole land of Havilah, where there is gold;",
    "and the gold of that land is good. Bdellium and onyx stone are also there.",
    "The name of the second river is Gihon. It is the same river that flows through the whole land of Cush.",
    "The name of the third river is Hiddekel. This is the one which flows in front of Assyria. The fourth river is the Euphrates.",
    "Yahweh God took the man, and put him into the garden of Eden to cultivate and keep it.",
    "Yahweh God commanded the man, saying, “You may freely eat of every tree of the garden;",
    "but you shall not eat of the tree of the knowledge of good and evil; for in the day that you eat of it, you will surely die.”",
    "Yahweh God said, “It is not good for the man to be alone. I will make him a helper comparable to him.”",
    "Out of the ground Yahweh God formed every animal of the field, and every bird of the sky, and brought them to the man to see what he would call them. Whatever the man called every living creature became its name.",
    "The man gave names to all livestock, and to the birds of the sky, and to every animal of the field; but for man there was not found a helper comparable to him.",
    "Yahweh God caused the man to fall into a deep sleep. As the man slept, he took one of his ribs, and closed up the flesh in its place.",
    "Yahweh God made a woman from the rib which he had taken from the man, and brought her to the man.",
    "The man said, “This is now bone of my bones, and flesh of my flesh. She will be called ‘woman,’ because she was taken out of Man.”",
    "Therefore a man will leave his father and his mother, and will join with his wife, and they will be one flesh.",
    "The man and his wife were both naked, and they were not ashamed.",
  ],
  "gen 3": [
    "Now the serpent was more subtle than any animal of the field which Yahweh God had made. He said to the woman, “Has God really said, ‘You shall not eat of any tree of the garden?’”",
    "The woman said to the serpent, “We may eat fruit from the trees of the garden,",
    "but not the fruit of the tree which is in the middle of the garden. God has said, ‘You shall not eat of it. You shall not touch it, lest you die.’”",
    "The serpent said to the woman, “You won’t really die,",
    "for God knows that in the day you eat it, your eyes will be opened, and you will be like God, knowing good and evil.”",
    "When the woman saw that the tree was good for food, and that it was a delight to the eyes, and that the tree was to be desired to make one wise, she took some of its fruit, and ate; and she gave some to her husband with her, and he ate it, too.",
    "Their eyes were opened, and they both knew that they were naked. They sewed fig leaves together, and made coverings for themselves.",
    "They heard Yahweh God’s voice walking in the garden in the cool of the day, and the man and his wife hid themselves from the presence of Yahweh God among the trees of the garden.",
    "Yahweh God called to the man, and said to him, “Where are you?”",
    "The man said, “I heard your voice in the garden, and I was afraid, because I was naked; and I hid myself.”",
    "God said, “Who told you that you were naked? Have you eaten from the tree that I commanded you not to eat from?”",
    "The man said, “The woman whom you gave to be with me, she gave me fruit from the tree, and I ate it.”",
    "Yahweh God said to the woman, “What have you done?” The woman said, “The serpent deceived me, and I ate.”",
    "Yahweh God said to the serpent, “Because you have done this, you are cursed above all livestock, and above every animal of the field. You shall go on your belly and you shall eat dust all the days of your life.",
    "I will put hostility between you and the woman, and between your offspring and her offspring. He will bruise your head, and you will bruise his heel.”",
    "To the woman he said, “I will greatly multiply your pain in childbirth. In pain you will bear children. Your desire will be for your husband, and he will rule over you.”",
    "To Adam he said, “Because you have listened to your wife’s voice, and ate from the tree, about which I commanded you, saying, ‘You shall not eat of it,’ the ground is cursed for your sake. You will eat from it with much labor all the days of your life.",
    "It will yield thorns and thistles to you; and you will eat the herb of the field.",
    "By the sweat of your face will you eat bread until you return to the ground, for out of it you were taken. For you are dust, and to dust you shall return.”",
    "The man called his wife Eve because she would be the mother of all the living.",
    "Yahweh God made coats of animal skins for Adam and for his wife, and clothed them.",
    "Yahweh God said, “Behold, the man has become like one of us, knowing good and evil. Now, lest he reach out his hand, and also take of the tree of life, and eat, and live forever—”",
    "Therefore Yahweh God sent him out from the garden of Eden, to till the ground from which he was taken.",
    "So he drove out the man; and he placed cherubim at the east of the garden of Eden, and a flaming sword which turned every way, to guard the way to the tree of life.",
  ],
  "joh 2": [
    "The third day, there was a marriage in Cana of Galilee. Jesus’ mother was there.",
    "Jesus also was invited, with his disciples, to the marriage.",
    "When the wine ran out, Jesus’ mother said to him, “They have no wine.”",
    "Jesus said to her, “Woman, what does that have to do with you and me? My hour has not yet come.”",
    "His mother said to the servants, “Whatever he says to you, do it.”",
    "Now there were six water pots of stone set there after the Jews’ way of purifying, containing two or three metretes apiece.",
    "Jesus said to them, “Fill the water pots with water.” They filled them up to the brim.",
    "He said to them, “Now draw some out, and take it to the ruler of the feast.” So they took it.",
    "When the ruler of the feast tasted the water now become wine, and didn’t know where it came from (but the servants who had drawn the water knew), the ruler of the feast called the bridegroom,",
    "and said to him, “Everyone serves the good wine first, and when the guests have drunk freely, then that which is worse. You have kept the good wine until now!”",
    "This beginning of his signs Jesus did in Cana of Galilee, and revealed his glory; and his disciples believed in him.",
    "After this, he went down to Capernaum, he, and his mother, his brothers, and his disciples; and they stayed there a few days.",
    "The Passover of the Jews was at hand, and Jesus went up to Jerusalem.",
    "He found in the temple those who sold oxen, sheep, and doves, and the changers of money sitting.",
    "He made a whip of cords, and threw all out of the temple, both the sheep and the oxen; and he poured out the changers’ money, and overthrew their tables.",
    "To those who sold the doves, he said, “Take these things out of here! Don’t make my Father’s house a marketplace!”",
    "His disciples remembered that it was written, “Zeal for your house will eat me up.”",
    "The Jews therefore answered him, “What sign do you show us, seeing that you do these things?”",
    "Jesus answered them, “Destroy this temple, and in three days I will raise it up.”",
    "The Jews therefore said, “It took forty-six years to build this temple! Will you raise it up in three days?”",
    "But he spoke of the temple of his body.",
    "When therefore he was raised from the dead, his disciples remembered that he said this, and they believed the Scripture, and the word which Jesus had said.",
    "Now when he was in Jerusalem at the Passover, during the feast, many believed in his name, observing his signs which he did.",
    "But Jesus didn’t entrust himself to them, because he knew everyone,",
    "and because he didn’t need for anyone to testify concerning man; for he himself knew what was in man.",
  ],
  "joh 3": [
    "Now there was a man of the Pharisees named Nicodemus, a ruler of the Jews.",
    "The same came to him by night, and said to him, “Rabbi, we know that you are a teacher come from God, for no one can do these signs that you do, unless God is with him.”",
    "Jesus answered him, “Most certainly, I tell you, unless one is born anew, he can’t see God’s Kingdom.”",
    "Nicodemus said to him, “How can a man be born when he is old? Can he enter a second time into his mother’s womb, and be born?”",
    "Jesus answered, “Most certainly I tell you, unless one is born of water and spirit, he can’t enter into God’s Kingdom.",
    "That which is born of the flesh is flesh. That which is born of the Spirit is spirit.",
    "Don’t marvel that I said to you, ‘You must be born anew.’",
    "The wind blows where it wants to, and you hear its sound, but don’t know where it comes from and where it is going. So is everyone who is born of the Spirit.”",
    "Nicodemus answered him, “How can these things be?”",
    "Jesus answered him, “Are you the teacher of Israel, and don’t understand these things?",
    "Most certainly I tell you, we speak that which we know, and testify of that which we have seen, and you don’t receive our witness.",
    "If I told you earthly things and you don’t believe, how will you believe if I tell you heavenly things?",
    "No one has ascended into heaven, but he who descended out of heaven, the Son of Man, who is in heaven.",
    "As Moses lifted up the serpent in the wilderness, even so must the Son of Man be lifted up,",
    "that whoever believes in him should not perish, but have eternal life.",
    "For God so loved the world, that he gave his one and only Son, that whoever believes in him should not perish, but have eternal life.",
    "For God didn’t send his Son into the world to judge the world, but that the world should be saved through him.",
    "He who believes in him is not judged. He who doesn’t believe has been judged already, because he has not believed in the name of the one and only Son of God.",
    "This is the judgment, that the light has come into the world, and men loved the darkness rather than the light; for their works were evil.",
    "For everyone who does evil hates the light, and doesn’t come to the light, lest his works would be exposed.",
    "But he who does the truth comes to the light, that his works may be revealed, that they have been done in God.”",
    "After these things, Jesus came with his disciples into the land of Judea. He stayed there with them, and baptized.",
    "John also was baptizing in Enon near Salim, because there was much water there. They came, and were baptized.",
    "For John was not yet thrown into prison.",
    "There arose therefore a questioning on the part of John’s disciples with some Jews about purification.",
    "They came to John, and said to him, “Rabbi, he who was with you beyond the Jordan, to whom you have testified, behold, the same baptizes, and everyone is coming to him.”",
    "John answered, “A man can receive nothing, unless it has been given him from heaven.",
    "You yourselves testify that I said, ‘I am not the Christ,’ but, ‘I have been sent before him.’",
    "He who has the bride is the bridegroom; but the friend of the bridegroom, who stands and hears him, rejoices greatly because of the bridegroom’s voice. This, my joy, therefore is made full.",
    "He must increase, but I must decrease.",
    "He who comes from above is above all. He who is from the earth belongs to the earth, and speaks of the earth. He who comes from heaven is above all.",
    "What he has seen and heard, of that he testifies; and no one receives his witness.",
    "He who has received his witness has set his seal to this, that God is true.",
    "For he whom God has sent speaks the words of God; for God gives the Spirit without measure.",
    "The Father loves the Son, and has given all things into his hand.",
    "One who believes in the Son has eternal life, but one who disobeys the Son won’t see life, but the wrath of God remains on him.”",
  ],
  "joh 4": [
    "Therefore when the Lord knew that the Pharisees had heard that Jesus was making and baptizing more disciples than John",
    "(although Jesus himself didn’t baptize, but his disciples),",
    "he left Judea, and departed into Galilee.",
    "He needed to pass through Samaria.",
    "So he came to a city of Samaria, called Sychar, near the parcel of ground that Jacob gave to his son, Joseph.",
    "Jacob’s well was there. Jesus therefore, being tired from his journey, sat down by the well. It was about the sixth hour.",
    "A woman of Samaria came to draw water. Jesus said to her, “Give me a drink.”",
    "For his disciples had gone away into the city to buy food.",
    "The Samaritan woman therefore said to him, “How is it that you, being a Jew, ask for a drink from me, a Samaritan woman?” (For Jews have no dealings with Samaritans.)",
    "Jesus answered her, “If you knew the gift of God, and who it is who says to you, ‘Give me a drink,’ you would have asked him, and he would have given you living water.”",
    "The woman said to him, “Sir, you have nothing to draw with, and the well is deep. So where do you get that living water?",
    "Are you greater than our father, Jacob, who gave us the well, and drank of it himself, as did his children, and his livestock?”",
    "Jesus answered her, “Everyone who drinks of this water will thirst again,",
    "but whoever drinks of the water that I will give him will never thirst again; but the water that I will give him will become in him a well of water springing up to eternal life.”",
    "The woman said to him, “Sir, give me this water, so that I don’t get thirsty, neither come all the way here to draw.”",
    "Jesus said to her, “Go, call your husband, and come here.”",
    "The woman answered, “I have no husband.” Jesus said to her, “You said well, ‘I have no husband,’",
    "for you have had five husbands; and he whom you now have is not your husband. This you have said truly.”",
    "The woman said to him, “Sir, I perceive that you are a prophet.",
    "Our fathers worshiped in this mountain, and you Jews say that in Jerusalem is the place where people ought to worship.”",
    "Jesus said to her, “Woman, believe me, the hour comes, when neither in this mountain, nor in Jerusalem, will you worship the Father.",
    "You worship that which you don’t know. We worship that which we know; for salvation is from the Jews.",
    "But the hour comes, and now is, when the true worshipers will worship the Father in spirit and truth, for the Father seeks such to be his worshipers.",
    "God is spirit, and those who worship him must worship in spirit and truth.”",
    "The woman said to him, “I know that Messiah comes, he who is called Christ. When he has come, he will declare to us all things.”",
    "Jesus said to her, “I am he, the one who speaks to you.”",
    "At this, his disciples came. They marveled that he was speaking with a woman; yet no one said, “What are you looking for?” or, “Why do you speak with her?”",
    "So the woman left her water pot, and went away into the city, and said to the people,",
    "“Come, see a man who told me everything that I did. Can this be the Christ?”",
    "They went out of the city, and were coming to him.",
    "In the meanwhile, the disciples urged him, saying, “Rabbi, eat.”",
    "But he said to them, “I have food to eat that you don’t know about.”",
    "The disciples therefore said to one another, “Has anyone brought him something to eat?”",
    "Jesus said to them, “My food is to do the will of him who sent me, and to accomplish his work.",
    "Don’t you say, ‘There are yet four months until the harvest?’ Behold, I tell you, lift up your eyes, and look at the fields, that they are white for harvest already.",
    "He who reaps receives wages, and gathers fruit to eternal life; that both he who sows and he who reaps may rejoice together.",
    "For in this the saying is true, ‘One sows, and another reaps.’",
    "I sent you to reap that for which you haven’t labored. Others have labored, and you have entered into their labor.”",
    "From that city many of the Samaritans believed in him because of the word of the woman, who testified, “He told me everything that I did.”",
    "So when the Samaritans came to him, they begged him to stay with them. He stayed there two days.",
    "Many more believed because of his word.",
    "They said to the woman, “Now we believe, not because of your speaking; for we have heard for ourselves, and know that this is indeed the Christ, the Savior of the world.”",
    "After the two days he went out from there and went into Galilee.",
    "For Jesus himself testified that a prophet has no honor in his own country.",
    "So when he came into Galilee, the Galileans received him, having seen all the things that he did in Jerusalem at the feast, for they also went to the feast.",
    "Jesus came therefore again to Cana of Galilee, where he made the water into wine. There was a certain nobleman whose son was sick at Capernaum.",
    "When he heard that Jesus had come out of Judea into Galilee, he went to him, and begged him that he would come down and heal his son, for he was at the point of death.",
    "Jesus therefore said to him, “Unless you see signs and wonders, you will in no way believe.”",
    "The nobleman said to him, “Sir, come down before my child dies.”",
    "Jesus said to him, “Go your way. Your son lives.” The man believed the word that Jesus spoke to him, and he went his way.",
    "As he was now going down, his servants met him and reported, saying “Your child lives!”",
    "So he inquired of them the hour when he began to get better. They said therefore to him, “Yesterday at the seventh hour, the fever left him.”",
    "So the father knew that it was at that hour in which Jesus said to him, “Your son lives.” He believed, as did his whole house.",
    "This is again the second sign that Jesus did, having come out of Judea into Galilee.",
  ],
};
