// The passages the study guides cover, in three public-domain English
// translations (the UX demo's src/bible.ts, STUDY-5). Verse numbers only;
// `scripture.ts` adds references and reading-pace timings.

interface PassageText {
  /** Book id as core's catalog names it ("gen", "luk", "joh"). */
  book: string;
  chapter: number;
  /** Translation code -> [verse, text] in order. */
  by: Record<string, [number, string][]>;
}

export const PASSAGE_TEXTS: PassageText[] = [
  { book: "gen", chapter: 2, by: {
    BSB: [
      [4, "This is the account of the heavens and the earth when they were created, in the day that the LORD God made them."],
      [5, "Now no shrub of the field had yet appeared on the earth, nor had any plant of the field sprouted; for the LORD God had not yet sent rain upon the earth, and there was no man to cultivate the ground."],
      [6, "But springs welled up from the earth and watered the whole surface of the ground."],
      [7, "Then the LORD God formed man from the dust of the ground and breathed the breath of life into his nostrils, and the man became a living being."],
      [8, "And the LORD God planted a garden in Eden, in the east, where He placed the man He had formed."],
      [9, "Out of the ground the LORD God gave growth to every tree that is pleasing to the eye and good for food. And in the middle of the garden were the tree of life and the tree of the knowledge of good and evil."],
      [10, "Now a river flowed out of Eden to water the garden, and from there it branched into four headwaters:"],
      [11, "The name of the first river is Pishon; it winds through the whole land of Havilah, where there is gold."],
      [12, "And the gold of that land is pure, and bdellium and onyx are found there."],
      [13, "The name of the second river is Gihon; it winds through the whole land of Cush."],
      [14, "The name of the third river is Hiddekel; it runs along the east side of Assyria. And the fourth river is the Euphrates."],
      [15, "Then the LORD God took the man and placed him in the Garden of Eden to cultivate and keep it."],
      [16, "And the LORD God commanded him, “You may eat freely from every tree of the garden,"],
      [17, "but you must not eat from the tree of the knowledge of good and evil; for in the day that you eat of it, you will surely die.”"],
      [18, "The LORD God also said, “It is not good for the man to be alone. I will make for him a suitable helper.”"],
      [19, "And out of the ground the LORD God formed every beast of the field and every bird of the air, and He brought them to the man to see what he would name each one. And whatever the man called each living creature, that was its name."],
      [20, "The man gave names to all the livestock, to the birds of the air, and to every beast of the field. But for Adam no suitable helper was found."],
      [21, "So the LORD God caused the man to fall into a deep sleep, and while he slept, He took one of the man’s ribs and closed up the area with flesh."],
      [22, "And from the rib that the LORD God had taken from the man, He made a woman and brought her to him."],
      [23, "And the man said: “This is now bone of my bones and flesh of my flesh; she shall be called ‘woman,’ for out of man she was taken.”"],
      [24, "For this reason a man will leave his father and mother and be united to his wife, and they will become one flesh."],
      [25, "And the man and his wife were both naked, and they were not ashamed."],
    ],
    WEB: [
      [4, "This is the history of the generations of the heavens and of the earth when they were created, in the day that Yahweh God made the earth and the heavens."],
      [5, "No plant of the field was yet in the earth, and no herb of the field had yet sprung up; for Yahweh God had not caused it to rain on the earth. There was not a man to till the ground,"],
      [6, "but a mist went up from the earth, and watered the whole surface of the ground."],
      [7, "Yahweh God formed man from the dust of the ground, and breathed into his nostrils the breath of life; and man became a living soul."],
      [8, "Yahweh God planted a garden eastward, in Eden, and there he put the man whom he had formed."],
      [9, "Out of the ground Yahweh God made every tree to grow that is pleasant to the sight, and good for food, including the tree of life in the middle of the garden and the tree of the knowledge of good and evil."],
      [10, "A river went out of Eden to water the garden; and from there it was parted, and became the source of four rivers."],
      [11, "The name of the first is Pishon: it flows through the whole land of Havilah, where there is gold;"],
      [12, "and the gold of that land is good. Bdellium and onyx stone are also there."],
      [13, "The name of the second river is Gihon. It is the same river that flows through the whole land of Cush."],
      [14, "The name of the third river is Hiddekel. This is the one which flows in front of Assyria. The fourth river is the Euphrates."],
      [15, "Yahweh God took the man, and put him into the garden of Eden to cultivate and keep it."],
      [16, "Yahweh God commanded the man, saying, “You may freely eat of every tree of the garden;"],
      [17, "but you shall not eat of the tree of the knowledge of good and evil; for in the day that you eat of it, you will surely die.”"],
      [18, "Yahweh God said, “It is not good for the man to be alone. I will make him a helper comparable to him.”"],
      [19, "Out of the ground Yahweh God formed every animal of the field, and every bird of the sky, and brought them to the man to see what he would call them. Whatever the man called every living creature became its name."],
      [20, "The man gave names to all livestock, and to the birds of the sky, and to every animal of the field; but for man there was not found a helper comparable to him."],
      [21, "Yahweh God caused the man to fall into a deep sleep. As the man slept, he took one of his ribs, and closed up the flesh in its place."],
      [22, "Yahweh God made a woman from the rib which he had taken from the man, and brought her to the man."],
      [23, "The man said, “This is now bone of my bones, and flesh of my flesh. She will be called ‘woman,’ because she was taken out of Man.”"],
      [24, "Therefore a man will leave his father and his mother, and will join with his wife, and they will be one flesh."],
      [25, "The man and his wife were both naked, and they were not ashamed."],
    ],
    KJV: [
      [4, "These are the generations of the heavens and of the earth when they were created, in the day that the LORD God made the earth and the heavens,"],
      [5, "And every plant of the field before it was in the earth, and every herb of the field before it grew: for the LORD God had not caused it to rain upon the earth, and there was not a man to till the ground."],
      [6, "But there went up a mist from the earth, and watered the whole face of the ground."],
      [7, "And the LORD God formed man of the dust of the ground, and breathed into his nostrils the breath of life; and man became a living soul."],
      [8, "And the LORD God planted a garden eastward in Eden; and there he put the man whom he had formed."],
      [9, "And out of the ground made the LORD God to grow every tree that is pleasant to the sight, and good for food; the tree of life also in the midst of the garden, and the tree of knowledge of good and evil."],
      [10, "And a river went out of Eden to water the garden; and from thence it was parted, and became into four heads."],
      [11, "The name of the first is Pison: that is it which compasseth the whole land of Havilah, where there is gold;"],
      [12, "And the gold of that land is good: there is bdellium and the onyx stone."],
      [13, "And the name of the second river is Gihon: the same is it that compasseth the whole land of Ethiopia."],
      [14, "And the name of the third river is Hiddekel: that is it which goeth toward the east of Assyria. And the fourth river is Euphrates."],
      [15, "And the LORD God took the man, and put him into the garden of Eden to dress it and to keep it."],
      [16, "And the LORD God commanded the man, saying, Of every tree of the garden thou mayest freely eat:"],
      [17, "But of the tree of the knowledge of good and evil, thou shalt not eat of it: for in the day that thou eatest thereof thou shalt surely die."],
      [18, "And the LORD God said, It is not good that the man should be alone; I will make him an help meet for him."],
      [19, "And out of the ground the LORD God formed every beast of the field, and every fowl of the air; and brought them unto Adam to see what he would call them: and whatsoever Adam called every living creature, that was the name thereof."],
      [20, "And Adam gave names to all cattle, and to the fowl of the air, and to every beast of the field; but for Adam there was not found an help meet for him."],
      [21, "And the LORD God caused a deep sleep to fall upon Adam, and he slept: and he took one of his ribs, and closed up the flesh instead thereof;"],
      [22, "And the rib, which the LORD God had taken from man, made he a woman, and brought her unto the man."],
      [23, "And Adam said, This is now bone of my bones, and flesh of my flesh: she shall be called Woman, because she was taken out of Man."],
      [24, "Therefore shall a man leave his father and his mother, and shall cleave unto his wife: and they shall be one flesh."],
      [25, "And they were both naked, the man and his wife, and were not ashamed."],
    ],
  } },
  { book: "luk", chapter: 15, by: {
    BSB: [
      [11, "Jesus continued: “There was a man who had two sons."],
      [12, "The younger son said to him, ‘Father, give me my share of the estate.’ So he divided his property between them."],
      [13, "After a few days, the younger son got all his belongings together and went off to a distant country, where he squandered his wealth in wild living."],
      [14, "After he had spent all he had, a severe famine swept through that country, and he began to be in need."],
      [15, "So he went and hired himself out to a citizen of that country, who sent him into his fields to feed the pigs."],
      [16, "He longed to fill his belly with the pods the pigs were eating, but no one would give him a thing."],
      [17, "Finally he came to his senses and said, ‘How many of my father’s hired servants have plenty of food? But here I am, starving to death!"],
      [18, "I will get up and go back to my father and say to him, “Father, I have sinned against heaven and against you."],
      [19, "I am no longer worthy to be called your son. Make me like one of your hired servants.”’"],
      [20, "So he got up and went to his father. But while he was still in the distance, his father saw him and was filled with compassion. He ran to his son, embraced him, and kissed him."],
      [21, "The son declared, ‘Father, I have sinned against heaven and against you. I am no longer worthy to be called your son.’"],
      [22, "But the father said to his servants, ‘Quick! Bring the best robe and put it on him. Put a ring on his finger and sandals on his feet."],
      [23, "Bring the fattened calf and kill it. Let us feast and celebrate."],
      [24, "For this son of mine was dead and is alive again! He was lost and is found!’ So they began to celebrate."],
      [25, "Meanwhile the older son was in the field, and as he approached the house, he heard music and dancing."],
      [26, "So he called one of the servants and asked what was going on."],
      [27, "‘Your brother has returned,’ he said, ‘and your father has killed the fattened calf, because he has him back safe and sound.’"],
      [28, "The older son became angry and refused to go in. So his father came out and pleaded with him."],
      [29, "But he answered his father, ‘Look, all these years I have served you and never disobeyed a commandment of yours. Yet you never gave me even a young goat so I could celebrate with my friends."],
      [30, "But when this son of yours returns from squandering your wealth with prostitutes, you kill the fattened calf for him!’"],
      [31, "‘Son, you are always with me,’ the father said, ‘and all that is mine is yours."],
      [32, "But it was fitting to celebrate and be glad, because this brother of yours was dead and is alive again; he was lost and is found.’”"],
    ],
    WEB: [
      [11, "He said, “A certain man had two sons."],
      [12, "The younger of them said to his father, ‘Father, give me my share of your property.’ So he divided his livelihood between them."],
      [13, "Not many days after, the younger son gathered all of this together and traveled into a far country. There he wasted his property with riotous living."],
      [14, "When he had spent all of it, there arose a severe famine in that country, and he began to be in need."],
      [15, "He went and joined himself to one of the citizens of that country, and he sent him into his fields to feed pigs."],
      [16, "He wanted to fill his belly with the pods that the pigs ate, but no one gave him any."],
      [17, "But when he came to himself he said, ‘How many hired servants of my father’s have bread enough to spare, and I’m dying with hunger!"],
      [18, "I will get up and go to my father, and will tell him, “Father, I have sinned against heaven, and in your sight."],
      [19, "I am no more worthy to be called your son. Make me as one of your hired servants.”’"],
      [20, "“He arose, and came to his father. But while he was still far off, his father saw him, and was moved with compassion, and ran, fell on his neck, and kissed him."],
      [21, "The son said to him, ‘Father, I have sinned against heaven, and in your sight. I am no longer worthy to be called your son.’"],
      [22, "“But the father said to his servants, ‘Bring out the best robe, and put it on him. Put a ring on his hand, and sandals on his feet."],
      [23, "Bring the fattened calf, kill it, and let’s eat, and celebrate;"],
      [24, "for this, my son, was dead, and is alive again. He was lost, and is found.’ Then they began to celebrate."],
      [25, "“Now his elder son was in the field. As he came near to the house, he heard music and dancing."],
      [26, "He called one of the servants to him, and asked what was going on."],
      [27, "He said to him, ‘Your brother has come, and your father has killed the fattened calf, because he has received him back safe and healthy.’"],
      [28, "But he was angry, and would not go in. Therefore his father came out, and begged him."],
      [29, "But he answered his father, ‘Behold, these many years I have served you, and I never disobeyed a commandment of yours, but you never gave me a goat, that I might celebrate with my friends."],
      [30, "But when this your son came, who has devoured your living with prostitutes, you killed the fattened calf for him.’"],
      [31, "“He said to him, ‘Son, you are always with me, and all that is mine is yours."],
      [32, "But it was appropriate to celebrate and be glad, for this, your brother, was dead, and is alive again. He was lost, and is found.’”"],
    ],
    KJV: [
      [11, "And he said, A certain man had two sons:"],
      [12, "And the younger of them said to his father, Father, give me the portion of goods that falleth to me. And he divided unto them his living."],
      [13, "And not many days after the younger son gathered all together, and took his journey into a far country, and there wasted his substance with riotous living."],
      [14, "And when he had spent all, there arose a mighty famine in that land; and he began to be in want."],
      [15, "And he went and joined himself to a citizen of that country; and he sent him into his fields to feed swine."],
      [16, "And he would fain have filled his belly with the husks that the swine did eat: and no man gave unto him."],
      [17, "And when he came to himself, he said, How many hired servants of my father’s have bread enough and to spare, and I perish with hunger!"],
      [18, "I will arise and go to my father, and will say unto him, Father, I have sinned against heaven, and before thee,"],
      [19, "And am no more worthy to be called thy son: make me as one of thy hired servants."],
      [20, "And he arose, and came to his father. But when he was yet a great way off, his father saw him, and had compassion, and ran, and fell on his neck, and kissed him."],
      [21, "And the son said unto him, Father, I have sinned against heaven, and in thy sight, and am no more worthy to be called thy son."],
      [22, "But the father said to his servants, Bring forth the best robe, and put it on him; and put a ring on his hand, and shoes on his feet:"],
      [23, "And bring hither the fatted calf, and kill it; and let us eat, and be merry:"],
      [24, "For this my son was dead, and is alive again; he was lost, and is found. And they began to be merry."],
      [25, "Now his elder son was in the field: and as he came and drew nigh to the house, he heard musick and dancing."],
      [26, "And he called one of the servants, and asked what these things meant."],
      [27, "And he said unto him, Thy brother is come; and thy father hath killed the fatted calf, because he hath received him safe and sound."],
      [28, "And he was angry, and would not go in: therefore came his father out, and intreated him."],
      [29, "And he answering said to his father, Lo, these many years do I serve thee, neither transgressed I at any time thy commandment: and yet thou never gavest me a kid, that I might make merry with my friends:"],
      [30, "But as soon as this thy son was come, which hath devoured thy living with harlots, thou hast killed for him the fatted calf."],
      [31, "And he said unto him, Son, thou art ever with me, and all that I have is thine."],
      [32, "It was meet that we should make merry, and be glad: for this thy brother was dead, and is alive again; and was lost, and is found."],
    ],
  } },
  { book: "joh", chapter: 3, by: {
    BSB: [
      [1, "Now there was a Pharisee named Nicodemus, a leader of the Jews."],
      [2, "He came to Jesus at night and said, “Rabbi, we know that You are a teacher who has come from God. For no one could perform the signs You are doing if God were not with him.”"],
      [3, "Jesus replied, “Truly, truly, I tell you, no one can see the kingdom of God unless he is born again.”"],
      [4, "“How can a man be born when he is old?” Nicodemus asked. “Can he enter his mother’s womb a second time to be born?”"],
      [5, "Jesus answered, “Truly, truly, I tell you, no one can enter the kingdom of God unless he is born of water and the Spirit."],
      [6, "Flesh is born of flesh, but spirit is born of the Spirit."],
      [7, "Do not be amazed that I said, ‘You must be born again.’"],
      [8, "The wind blows where it wishes. You hear its sound, but you do not know where it comes from or where it is going. So it is with everyone born of the Spirit.”"],
      [9, "“How can this be?” Nicodemus asked."],
      [10, "“You are Israel’s teacher,” said Jesus, “and you do not understand these things?"],
      [11, "Truly, truly, I tell you, we speak of what we know, and we testify to what we have seen. And yet you people do not accept our testimony."],
      [12, "If I have told you about earthly things and you do not believe, how will you believe if I tell you about heavenly things?"],
      [13, "No one has ascended into heaven except the One who descended from heaven—the Son of Man."],
      [14, "Just as Moses lifted up the snake in the wilderness, so the Son of Man must be lifted up,"],
      [15, "that everyone who believes in Him may have eternal life."],
      [16, "For God so loved the world that He gave His one and only Son, that everyone who believes in Him shall not perish but have eternal life."],
      [17, "For God did not send His Son into the world to condemn the world, but to save the world through Him."],
      [18, "Whoever believes in Him is not condemned, but whoever does not believe has already been condemned, because he has not believed in the name of God’s one and only Son."],
      [19, "And this is the verdict: The Light has come into the world, but men loved the darkness rather than the Light because their deeds were evil."],
      [20, "Everyone who does evil hates the Light, and does not come into the Light for fear that his deeds will be exposed."],
      [21, "But whoever practices the truth comes into the Light, so that it may be seen clearly that what he has done has been accomplished in God.”"],
    ],
    WEB: [
      [1, "Now there was a man of the Pharisees named Nicodemus, a ruler of the Jews."],
      [2, "The same came to him by night, and said to him, “Rabbi, we know that you are a teacher come from God, for no one can do these signs that you do, unless God is with him.”"],
      [3, "Jesus answered him, “Most certainly I tell you, unless one is born anew, he can’t see God’s Kingdom.”"],
      [4, "Nicodemus said to him, “How can a man be born when he is old? Can he enter a second time into his mother’s womb, and be born?”"],
      [5, "Jesus answered, “Most certainly I tell you, unless one is born of water and spirit, he can’t enter into God’s Kingdom."],
      [6, "That which is born of the flesh is flesh. That which is born of the Spirit is spirit."],
      [7, "Don’t marvel that I said to you, ‘You must be born anew.’"],
      [8, "The wind blows where it wants to, and you hear its sound, but don’t know where it comes from and where it is going. So is everyone who is born of the Spirit.”"],
      [9, "Nicodemus answered him, “How can these things be?”"],
      [10, "Jesus answered him, “Are you the teacher of Israel, and don’t understand these things?"],
      [11, "Most certainly I tell you, we speak that which we know, and testify of that which we have seen, and you don’t receive our witness."],
      [12, "If I told you earthly things and you don’t believe, how will you believe if I tell you heavenly things?"],
      [13, "No one has ascended into heaven but he who descended out of heaven, the Son of Man, who is in heaven."],
      [14, "As Moses lifted up the serpent in the wilderness, even so must the Son of Man be lifted up,"],
      [15, "that whoever believes in him should not perish, but have eternal life."],
      [16, "For God so loved the world, that he gave his one and only Son, that whoever believes in him should not perish, but have eternal life."],
      [17, "For God didn’t send his Son into the world to judge the world, but that the world should be saved through him."],
      [18, "He who believes in him is not judged. He who doesn’t believe has been judged already, because he has not believed in the name of the one and only Son of God."],
      [19, "This is the judgment, that the light has come into the world, and men loved the darkness rather than the light, for their works were evil."],
      [20, "For everyone who does evil hates the light, and doesn’t come to the light, lest his works would be exposed."],
      [21, "But he who does the truth comes to the light, that his works may be revealed, that they have been done in God.”"],
    ],
    KJV: [
      [1, "There was a man of the Pharisees, named Nicodemus, a ruler of the Jews:"],
      [2, "The same came to Jesus by night, and said unto him, Rabbi, we know that thou art a teacher come from God: for no man can do these miracles that thou doest, except God be with him."],
      [3, "Jesus answered and said unto him, Verily, verily, I say unto thee, Except a man be born again, he cannot see the kingdom of God."],
      [4, "Nicodemus saith unto him, How can a man be born when he is old? can he enter the second time into his mother’s womb, and be born?"],
      [5, "Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God."],
      [6, "That which is born of the flesh is flesh; and that which is born of the Spirit is spirit."],
      [7, "Marvel not that I said unto thee, Ye must be born again."],
      [8, "The wind bloweth where it listeth, and thou hearest the sound thereof, but canst not tell whence it cometh, and whither it goeth: so is every one that is born of the Spirit."],
      [9, "Nicodemus answered and said unto him, How can these things be?"],
      [10, "Jesus answered and said unto him, Art thou a master of Israel, and knowest not these things?"],
      [11, "Verily, verily, I say unto thee, We speak that we do know, and testify that we have seen; and ye receive not our witness."],
      [12, "If I have told you earthly things, and ye believe not, how shall ye believe, if I tell you of heavenly things?"],
      [13, "And no man hath ascended up to heaven, but he that came down from heaven, even the Son of man which is in heaven."],
      [14, "And as Moses lifted up the serpent in the wilderness, even so must the Son of man be lifted up:"],
      [15, "That whosoever believeth in him should not perish, but have eternal life."],
      [16, "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life."],
      [17, "For God sent not his Son into the world to condemn the world; but that the world through him might be saved."],
      [18, "He that believeth on him is not condemned: but he that believeth not is condemned already, because he hath not believed in the name of the only begotten Son of God."],
      [19, "And this is the condemnation, that light is come into the world, and men loved darkness rather than light, because their deeds were evil."],
      [20, "For every one that doeth evil hateth the light, neither cometh to the light, lest his deeds should be reproved."],
      [21, "But he that doeth truth cometh to the light, that his deeds may be made manifest, that they are wrought in God."],
    ],
  } },
];
